### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by eclecticStreams** [kumardeo/blogger-pwa-github#3]
I set it up and its working at first then it suddenly stopped working

**Comment by kumardeo** [comment]
Can you please provide more information so I can check? For e.g. The forked repository, site url, etc.

**Comment by eclecticStreams** [comment]
The PWA is now working but it is not popping up for add to home screen
instead I will have to click the menu button at the top corner of my
browser to be able to install it.

Website: https://www.eclecticstreams.com.ng
GitHub: EclecticStreams/blogger-pwa-github

**Comment by kumardeo** [comment]
Looks like the manifest.json you changed is invalid json. Please make sure that json is valid, so that browser can parse it.

https://github.com/eclecticStreams/blogger-pwa-github/blob/7f6e326615e7b82fb5e69f61d05505f048e05fb9/app/manifest.json#L10-L12

You forgot to add a comma (,) after categories array.

**Comment by kumardeo** [comment]
There are multiple issues in the manifest.json file, you need to add comma after the handle_links:
https://github.com/eclecticStreams/blogger-pwa-github/blob/ad0780ea0345b980f55439be553070d59464c484/app/manifest.json#L149

You can validate your json here: https://jsonlint.com

After validating your json, commit the changes and clear cache of the site in browser.

**Comment by eclecticStreams** [comment]
I will check everything again and add the appropriate commas.


I'm add all those code because I want to package it to APK

**Comment by eclecticStreams** [comment]
I've added all the necessary commas and it's now showing in
https://www.eclecticstreams.com.ng/app/manifest.json

I presume it's now valid.
I still have some questions.
1. How do I make use of the notification, is it that it will automatically
notify all my PWA user when I send via one signal?
2. How do I prompt user to install our app or add to home screen?
3. How do I add offline support to my PWA?

**Comment by kumardeo** [comment]
You forgot one step in the tutorial, where you have to add the following in the head section:
```js
<script async="true" defer="true" src="/app/pwa.js" type="module"></script>
```
Go through the post one more time and make sure you did everything as stated in the post.

**Comment by eclecticStreams** [comment]
Reply my messages please

**Comment by kumardeo** [comment]
I visited your site, you are missing with things like adding the javascript (for non amp template). Once you load the pwa.js, service workers will be registered which allows you to send background notifications, offline page, app installation popup, etc.
A success info is logged by the javascript on successful registration. After making sure you did everything in tutorial, check the browser console for logs.

**Comment by eclecticStreams** [comment]
do you mean this section? if yes ive added it already

**Comment by eclecticStreams** [comment]
reply this also

**Comment by kumardeo** [comment]
The installation popup now appears. Please check it.

Confirm it if you are able to see the pop-up or 'Install app' button instead of 'Add to Homescreen'.

![20240229_135940.jpg](https://github.com/kumardeo/blogger-pwa-github/assets/86065483/e5d597fb-ce2f-4db8-9676-c04ccd200266)

**Comment by eclecticStreams** [comment]
Yes. I changed it from above the </body> to above the </head>.



Thanks

**Comment by eclecticStreams** [comment]
I've seen so many code on your site I want to add to my blogger website and
it's all requesting me to paste css code over the skin.

it won't affect each other if I add another css code over it

**Comment by kumardeo** [comment]
Closing issue since PWA is working as expected.

**Comment by eclecticStreams** [comment]
Ok, thanks for the update.
